version: 0.1
phases:
  install:
    commands:
      - npm install
      - aws cloudformation package --template-file template.yml --s3-bucket cw-to-slack-manabe-test --output-template-file template.sam.yml
artifacts:
  type: zip
  files:
    - template.yml
    - template.sam.yml
